# Generated by Django 5.2.14 on 2026-05-16 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('moves_used', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(choices=[('moves', 'Limited Moves'), ('timer', 'Timer Mode')], default='moves', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
